export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN='SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS='SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR='SETUP_USER_ERROR';
 
export const TOGGLE_SIDE_BAR='TOGGLE_SIDE_BAR';

export const LOG_OUT_USER='LOG_OUT_USER';


export const UPDATE_USER_BEGIN='UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR='UPDATE_USER_ERROR';

export const HANDLE_CHANGE='HANDLE_CHANGE';
export const CLEAR_VALUES='CLEAR_VALUES';


export const CREATE_INTERVIEW_BEGIN='CREATE_INTERVIEW_BEGIN';
export const CREATE_INTERVIEW_SUCCESS='CREATE_INTERVIEW_SUCCESS';
export const CREATE_INTERVIEW_ERROR='CREATE_INTERVIEW_ERROR';

export const GET_INTERVIEWS_BEGIN='GET_INTERVIEWS_BEGIN';
export const GET_INTERVIEWS_SUCCESS='GET_INTERVIEWS_SUCCESS';

export const SET_EDIT_JOB='SET_EDIT_JOB';

export const DELETE_JOB_BEGIN='DELETE_JOB_BEGIN';


export const EDIT_JOB_BEGIN='EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS='EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR='EDIT_JOB_ERROR';

export const SHOW_STATS_BEGIN='SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS='SHOW_STATS_SUCCESS';


export const CLEAR_FILTER='CLEAR_FILTER';

export const CHANGE_PAGE='CHANGE_PAGE';

export const GET_ADMIN_INTERVIEWS_BEGIN='GET_ADMIN_INTERVIEWS_BEGIN';
export const GET_ADMIN_INTERVIEWS_SUCCESS='GET_ADMIN_INTERVIEWS_SUCCESS';

